### PR TITLE
Developing

### PR DESCRIPTION
**Pull request by fabricio-garcia**
Released first developing version

### CODE REVIEW

**Comment by cochabambinoski** [comment]
will need stickler

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by cochabambinoski** [comment]
Hello,

There was an issue (Im not sure why yet) with the secondary branch, so I
was commiting to master branch or instead, helping to Fabricio this time,
so he can push it to the right place in the project in github, but we both
code at the same time and worked as a collaborative team.

Best regards

**Comment by fabricio-garcia** [comment]
Cochabambinoski was not able to push to the developing branch, but he was doing his parte. He already sent you an email.

**Pull request merged**
